In [1]:
import numpy as np

## Data Types and Attributes

In [2]:
# numpy's main data type is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 =  np.array([
    [1, 2, 3.4],
    [4, 5.2, 6]
])
a2

array([[1. , 2. , 3.4],
       [4. , 5.2, 6. ]])

In [5]:
a3 = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]
        ],
        [
            [10, 11, 12],
            [13, 14, 15],
            [16, 17, 18]
        ]
    ]
)
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
# dimensions 
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
# size
a1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
# data type
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
# type
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
a2

array([[1. , 2. , 3.4],
       [4. , 5.2, 6. ]])

In [16]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
# pandas and other majority of machine learning algorithms are build on top of numpy!

In [17]:
# creating a data frame using numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.4
1  4.0  5.2  6.0

## Creating arrays

In [19]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [21]:
# np.ones() creates an array filled with 1s.
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
ones.dtype

dtype('float64')

In [23]:
type(ones)

numpy.ndarray

In [24]:
# np.zeros() creates array filled with 0s.
zeros = np.zeros((2, 3))

In [25]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# np.arange() creates array with in given range with specified gap
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [27]:
# creating a random array
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[8, 8, 1, 0, 7],
       [0, 4, 0, 6, 4],
       [6, 0, 9, 9, 9]])

In [28]:
random_array.size

15

In [29]:
random_array.shape

(3, 5)

In [30]:
# creating a random array: method 2
random_array_2 = np.random.random((3,5))
random_array_2

array([[0.49515888, 0.03373452, 0.70220018, 0.19063091, 0.04845988],
       [0.96165149, 0.64457748, 0.19384205, 0.45054481, 0.42382943],
       [0.0176066 , 0.79967309, 0.27033846, 0.02324936, 0.21103246]])

In [32]:
# creating random array: method 3
random_array_3 = np.random.rand(3,5)
random_array_3

array([[0.85951121, 0.69219754, 0.02511217, 0.95788171, 0.68041854],
       [0.4445534 , 0.08468717, 0.71606426, 0.24851336, 0.35371794],
       [0.79805793, 0.82432079, 0.70634368, 0.75680741, 0.41019626]])

In [40]:
# pseudo random numbers
# basically we can use np.random.seed(seed=?) to get exact same random numbers every time.
# this will be beneficial if we need to get the exact same data as results when running the same notebook in another machine!
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(3,5))
random_array_4

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [39]:
np.random.seed(seed=10)
random_array_5 = np.random.random((3,5))
random_array_5

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981],
       [0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096]])